Repository bangumi/server, pull requests merged in 2023-05, with the labels that each got.

#344 fix: index/indexSubject table has soft delete
  cmd/gen/gorm/main.go
  dal/dao/chii_index.gen.go
  dal/dao/chii_index_related.gen.go
  dal/query/chii_index.gen.go
  dal/query/chii_index_related.gen.go
  go.mod
  go.sum
  internal/index/mysql_repository.go
  internal/index/mysql_repository_test.go
  internal/model/index.go
  openapi/v0.yaml
  web/handler/index/index.go
  web/res/index.go
Labels: size/M

#348 fix: limit 0 return nothing
  ctrl/update_episode_progress.go
  internal/episode/mysql_repository_test.go
Labels: size/S

#351 fix: reject unknown json field and response code
  web/json.go
  web/new.go
  web/res/error.go
Labels: size/M

#352 fix: missing subject collection record subject type
  ctrl/update_episode_progress.go
  ctrl/update_subject_collection.go
  internal/collections/domain.go
  internal/collections/infra/mysql_repo.go
  internal/collections/infra/mysql_repo_test.go
  internal/mocks/CollectionRepo.go
  web/handler/user/patch_subject_collection.go
  web/handler/user/patch_subject_collection_test.go
  web/handler/user/post_subject_collection_test.go
  web/handler/user/update_episode_collection_test.go
Labels: size/L
