Repository bangumi/server, pull requests merged in 2024-11, with the labels that each got.

#662 revert: disable img proxy for person grid image
  web/res/image.go
Labels: size/XS

#663 fix: filter nsfw on search
  internal/search/handle.go
  internal/search/handle_internal_test.go
Labels: size/S

#664 feat: add more fields for subject search
  internal/search/client.go
  internal/search/handle.go
  openapi/v0.yaml
  web/handler/subject/browse.go
  web/handler/subject/get.go
  web/res/character.go
  web/res/person.go
  web/res/subject.go
Labels: size/L

#666 fix: missing tag cached repo for canal
  canal/canal.go
Labels: size/XS

#667 metrics: add meta tags cached count
  internal/tag/cache_repo.go
Labels: size/S

#668 build: add commit date to docker tags
  .github/workflows/release-docker.yaml
Labels: size/XS

#669 perf: cache subject empty meta tags list
  internal/cachekey/cachekey.go
  internal/tag/cache_repo.go
  internal/tag/mysql_repo.go
Labels: size/S

#670 fix: ignore empty tag on search
  internal/search/client.go
  internal/search/handle.go
Labels: size/S

#671 feat: support searching character & person
  canal/canal.go
  canal/event.go
  canal/on_character.go
  canal/on_person.go
  canal/on_subject.go
  cmd/web/cmd.go
  internal/mocks/SearchClient.go
  internal/search/character/client.go
  internal/search/character/doc.go
  internal/search/character/event.go
  internal/search/character/handle.go
  internal/search/client.go
  internal/search/extractor.common.go
  internal/search/noop.go
  internal/search/person/client.go
  internal/search/person/doc.go
  internal/search/person/event.go
  internal/search/person/handle.go
  internal/search/search.go
  internal/search/searcher/client.go
  internal/search/subject/client.go
  internal/search/subject/doc.go
  internal/search/subject/doc_internal_test.go
  internal/search/subject/event.go
  internal/search/subject/handle.go
  internal/search/subject/handle_internal_test.go
  internal/search/subject/index_internal_test.go
  openapi/v0.yaml
  web/handler/character/character.go
  web/handler/character/get.go
  web/handler/search.go
  web/res/character.go
  web/routes.go
Labels: size/XXL

#672 fix: update example config for kafka topics
  config.example.yaml
Labels: size/XS

#674 fix: remove duplicate repo arg
  cmd/web/cmd.go
Labels: size/XS
