Repository bangumi/server, pull requests merged in 2025-04, with the labels that each got.

#780 style: migrade golangci-lint to v2
  .github/workflows/lint.yaml
  .golangci.yaml
  canal/canal.go
  cmd/archive/main.go
  cmd/gen/gorm/main.go
  cmd/web/cmd.go
  dal/new_test.go
  dal/utiltype/string.go
  internal/pkg/cache/redis.go
  internal/pkg/driver/mysql.go
  internal/pkg/test/fx.go
  internal/pkg/test/gorm.go
  internal/search/searcher/client.go
  internal/search/subject/handle.go
  web/accessor/accesor.go
  web/new_internal_test.go
  web/req/content_type.go
Labels: size/L

#787 fix: add rate limit
  web/new.go
  web/req/ban.lua
  web/req/rate-limit.go
Labels: size/L

#788 fix: cache subject
  internal/pkg/driver/mysql.go
  web/handler/subject/get_test.go
  web/handler/subject/related_subjects_test.go
  web/handler/subject/subject.go
Labels: size/S

#790 fix: make rate limit configurable
  config/config.go
  web/mw/ban.lua
  web/mw/rate-limit.go
  web/new.go
Labels: size/M

#791 refactor: use toml config
  .gitignore
  canal/canal.go
  canal/stream_kafka.go
  cmd/web/cmd.go
  config.example.toml
  config.example.yaml
  config/config.go
  internal/search/searcher/client.go
  readme.md
  taskfile.yaml
Labels: size/L

#792 fix: suppress client cancel error
  web/error.go
  web/mw/rate-limit.go
Labels: size/S

#793 fix: let cf cache some requests
  web/handler/character/get.go
  web/handler/person/get.go
  web/handler/subject/get.go
  web/res/cache-control.go
Labels: size/M

#794 fix: add cache to wiki requests
  web/handler/character/get.go
  web/handler/character/get_related_persons.go
  web/handler/character/get_related_subjects.go
  web/handler/person/get.go
  web/handler/person/get_related_characters.go
  web/handler/person/get_related_subjects.go
  web/handler/subject/get.go
  web/handler/subject/related_characters.go
  web/handler/subject/related_persons.go
  web/handler/subject/related_subjects.go
  web/res/cache-control.go
Labels: size/M

#795 feat(archive): export subject.MetaTags
  cmd/archive/main.go
Labels: size/S

#796 refactor: cleanup old code
  internal/pkg/generic/conv.go
  internal/pkg/generic/math.go
  web/session/manager.go
Labels: size/M

#797 fix: ban broken UA
  web/mw/ua/new.go
  web/new.go
  web/routes.go
Labels: size/M

#798 fix: user-agent check supports Animeko-beta
  web/mw/ua/new.go
Labels: size/XS

#799 fix: animeko UA check
  web/mw/ua/new.go
Labels: size/XS

#803 fix: server panic
  web/handler/index/subject.go
  web/req/index.go
Labels: size/XS

#804 chore: remove yaml
  go.mod
  go.sum
  package.json
  pkg/vars/index.go
  pkg/vars/relations.go.json
  pkg/vars/staffs.go.json
  scripts/build-common.mjs
Labels: size/XXL
